<?php
function queenattack_menu(){
    $items['queenattack'] = array(
        'title' => 'Queen Attack',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('queen_check_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['queenattack_success_page'] = array(
        'title' => 'Success',
        'page callback' => 'queenattack_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}
function queen_check_form(){
    $form['queen_coordinates'] = array(
        '#title' => 'Queen Coordinates',
        '#type' => 'textfield',
        '#description' => t('Enter the placement of the queen.'),
    );
    $form['piece_coordinates'] = array(
        '#title' => 'Piece Coordinates',
        '#type' => 'textfield',
        '#description' => t('Enter the placement of the piece that is being attacked.'),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Queen Attack',
    );
    return $form;
}
function queen_check_form_submit($form, &$form_state){
    $queen = $form_state['values']['queen_coordinates'];
    $piece = $form_state['values']['piece_coordinates'];
    if (substr_compare($queen, $piece, 0) == 0){
        $_SESSION['queen'] = "The queen will kill.";
        $form_state['redirect'] = 'queenattack_success_page';
    } elseif (substr_compare($queen, $piece, 0) != 0){
        $_SESSION['queen'] = 'The piece gets away!';
        $form_state['redirect'] = 'queenattack_success_page';
    }
}
function queenattack_success(){
    return $_SESSION['queen'];
}
